### ISSUE TITLE
Setup error 

### ISSUE THREAD

**Issue by peterbundgaard** [sayhicoelho/vue-firebase#1]
Hi Sayhicoelho 

Thx for this boilerplate. It's just what I've been searching for. However I struggle a bit with the setup. 

After I run npm install I copied the content from .env.example into a file called .env and then I pasted my data from Firebase project into the file.

When I launch the app with "npm run dev" I get "Compiled successfully", but when I open in the browser the Console throws the error "SyntaxError: Unexpected token ':'. Expected '}' to end an object literal." 
![skaermbillede 2018-09-06 kl 13 08 27](https://user-images.githubusercontent.com/33330904/45153919-fcaac300-b1d5-11e8-92dc-138bdb19f3cc.png)

What have I missed? 

Best regards 
Peter

**Comment by sayhicoelho** [comment]
Hey Peter!

I've cloned the project and it works with no errors. Can you say what is the NPM and NODE version you're running?

Please do these steps to work with the project:

1. create a folder
2. run `git clone https://github.com/sayhicoelho/vue-firebase.git`
3. copy the .env.example to .env (and paste your Firebase configurations)
4. run `npm run dev`
5. open `http://127.0.0.1:8080`

Please tell me if you're getting any error again.

**Comment by peterbundgaard** [comment]
Thx for fast reply @sayhicoelho :)

It's strange, i'm following exact those steps. (I just add "npm install" as step 3.)

**Node nem versions** 
"node": ">= 6.0.0",
"npm": ">= 3.0.0"

Could that be the problem?

**Comment by sayhicoelho** [comment]
Yes! I forgot `npm install`!

Try to update the NPM and NODE. I'm using NPM v5.5.1 and NODE v8.9.1.

Please check if the issue was solved.

Thx :-)

**Comment by peterbundgaard** [comment]
It still gives me the error. It's super weird. It seams so simple? 

**I updated to:** 
node v8.9.0
NPM v6.4.1

Do you have any other ideas?

**Comment by peterbundgaard** [comment]
I figured it out :-) I was new to .env files. I didn't know that you had to wrap the values in '"VALUE"' and not just "VALUE". Now it works like a charm. 

Thx

**Comment by sayhicoelho** [comment]
Whoool! My bad!

In [prod.env](https://github.com/sayhicoelho/vue-firebase/blob/master/config/prod.env.js) file you'll see the line `NODE_ENV: '"production"'`. Yes! I forgot it.

Thank you for remembering that we need to pass the values with '"VALUE"' instead of 'VALUE'.

I'll update my README.md. Thank you again, Peter! 👍
